'use strict';
const fs=require('fs'),path=require('path'),{execSync}=require('child_process');
const RAW=path.join(__dirname,'../data/raw'),OUT=path.join(__dirname,'../data/sql');
fs.mkdirSync(OUT,{recursive:true});
const CY=new Date();CY.setFullYear(CY.getFullYear()-5);
const CC=new Set(['DSQ','DTB','DXX','LWS','MKJ']);
function xz(f,l){console.log('['+l+'] Extracting');const t=path.join(RAW,'tmp_'+l);fs.mkdirSync(t,{recursive:true});execSync('unzip -o '+f+' -d '+t,{stdio:'ignore'});const js=fs.readdirSync(t).filter(x=>x.endsWith('.json'));const r=JSON.parse(fs.readFileSync(path.join(t,js[0]),'utf8'));console.log('['+l+'] records:'+r.results.length);return r.results;}
function esc(v){if(v===null||v===undefined||v==='')return 'NULL';if(typeof v==='object')v=JSON.stringify(v);return "'"+(String(v).replace(/'/g,"''").slice(0,500))+"'";}
function ok5(d){return d&&new Date(d)>=CY;}
function audit(l,data,fs2,id){console.log('['+l+'] AUDIT:');fs2.forEach(function(f){var n=data.filter(function(r){return r[f]&&r[f]!=='';}).length;console.log('  '+f+': '+n+'/'+data.length+' ('+(data.length?(n/data.length*100).toFixed(1):0)+'%)');});var ids=data.map(function(r){return r[id];}).filter(Boolean);console.log('  Dupes:'+(ids.length-new Set(ids).size));}
function pma(records){console.log('[PMA] Flattening');var f=records.filter(function(r){return CC.has(r.product_code)&&ok5(r.decision_date);});console.log('[PMA] rows:'+f.length);var cols=['pma_number','supplement_number','applicant','device_name','trade_name','product_code','advisory_committee','advisory_committee_description','supplement_type','supplement_reason','decision_code','decision_date','date_received','expedited_review_flag','docket_number','ao_statement','city','state','zip','generic_name'];var rows=f.map(function(r){return'('+cols.map(function(c){return esc(r[c]);}).join(',')+')';});var sql=['TRUNCATE TABLE pma_approvals;','INSERT INTO pma_approvals ('+cols.join(',')+')',' VALUES',rows.join(',')].join(' ');fs.writeFileSync(path.join(OUT,'pma_approvals.sql'),sql);audit('PMA',f,['pma_number','product_code','applicant','decision_date','decision_code'],'pma_number');return{rows:f.length,cols:cols.length};}
function rec(records){console.log('[RECALL] Flattening');var f=records.filter(function(r){return CC.has(r.product_code)&&ok5(r.event_date_initiated);});console.log('[RECALL] rows:'+f.length);var cols=['recall_number','recalling_firm','product_description','product_code','classification','voluntary_mandated','initial_firm_notification','distribution_pattern','reason_for_recall','status','event_date_initiated','event_date_posted','event_date_terminated','city','state','country','postal_code','product_quantity','action'];var rows=f.map(function(r){return'('+cols.map(function(c){return esc(r[c]);}).join(',')+')';});var sql=['TRUNCATE TABLE recalls;','INSERT INTO recalls ('+cols.join(',')+')',' VALUES',rows.join(',')].join(' ');fs.writeFileSync(path.join(OUT,'recalls.sql'),sql);audit('RECALL',f,['recall_number','product_code','recalling_firm','classification','event_date_initiated'],'recall_number');return{rows:f.length,cols:cols.length};}
(function(){var p=pma(xz(path.join(RAW,'pma.zip'),'PMA'));var r=rec(xz(path.join(RAW,'recall.zip'),'RECALL'));console.log('PHASE 3 COMPLETE');console.log('PMA: '+p.rows+' rows x '+p.cols+' cols');console.log('RECALL: '+r.rows+' rows x '+r.cols+' cols');})();